insert into pessoa (nome) values ('Mário');
insert into pessoa (nome) values ('Diogo');
insert into pessoa (nome) values ('Michel');
insert into pessoa (nome) values ('Isabela');
insert into pessoa (nome) values ('Florença');
insert into pessoa (nome) values ('Florenssa');
insert into pessoa (nome) values ('Açucena');
insert into pessoa (nome) values ('Assucena');
insert into pessoa (nome) values ('Gonçalo');
insert into pessoa (nome) values ('Gonssalo');
insert into pessoa (nome) values ('Marcos');
insert into pessoa (nome) values ('Marco');
insert into pessoa (nome) values ('Marcu');
insert into pessoa (nome) values ('Markos');
insert into pessoa (nome) values ('Martins');
insert into pessoa (nome) values ('Ricardo');
insert into pessoa (nome) values ('Rikardu');
insert into pessoa (nome) values ('Luíz');
insert into pessoa (nome) values ('Luis');
insert into pessoa (nome) values ('Amamda');
insert into pessoa (nome) values ('Amanda');
insert into pessoa (nome) values ('Priscila');
insert into pessoa (nome) values ('Pricila');
insert into pessoa (nome) values ('Plinio');
insert into pessoa (nome) values ('Plinho');
insert into pessoa (nome) values ('Pliniu');
insert into pessoa (nome) values ('Plinhu');
insert into pessoa (nome) values ('Matheus');
insert into pessoa (nome) values ('Mateus');
insert into pessoa (nome) values ('Hugo');
insert into pessoa (nome) values ('Ugo');
insert into pessoa (nome) values ('Quesia');
insert into pessoa (nome) values ('Quezia');
insert into pessoa (nome) values ('Marly');
insert into pessoa (nome) values ('Marli');
insert into pessoa (nome) values ('Guthierrez');
insert into pessoa (nome) values ('Gutierrez');
insert into pessoa (nome) values ('Gutierez');
insert into pessoa (nome) values ('Gutieres');
insert into pessoa (nome) values ('Phirmino');
insert into pessoa (nome) values ('Firmino');
insert into pessoa (nome) values ('Jose da silva');
insert into pessoa (nome) values ('José da Silva');
insert into pessoa (nome) values ('Joze da Cilva');
insert into pessoa (nome) values ('Jozé Ciuva');



